version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8080:80' # NPM의 HTTP 포트
      - '443:443' # NPM의 HTTPS 포트
      - '81:81'   # NPM의 관리자 웹 인터페이스 포트
    environment:
      TZ: "Asia/Seoul"
      DB_MYSQL_HOST: "host.docker.internal"
      DB_MYSQL_PORT: "3306"
      DB_MYSQL_USER: "root"
      DB_MYSQL_PASSWORD: ""
      DB_MYSQL_NAME: "cafe"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
